### ISSUE TITLE
Function to revoke role

### ISSUE THREAD

**Issue by thisisommore** [MyriadFlow/storefront_contracts#3]
<a href="https://github.com/thisisommore"><img src="https://avatars.githubusercontent.com/u/51229945?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [thisisommore](https://github.com/thisisommore)**
_Wednesday Feb 02, 2022 at 11:15 GMT_
_Originally opened as https://github.com/TheLazarusNetwork/marketplace-contracts/issues/17_

----

None

**Comment by Shachindra** [comment]
https://mumbai.polygonscan.com/address/0x013EFF13a04b7882eAd886D78F4FdB9D02502300#writeContract#F8
